### 개발용 컨트롤러 : batch job check
POST {{endpoint}}/batch/station-update
Content-Type: application/json

{
    "limit": 200
}


### 개발용 컨트롤러 : batch job status search
GET {{endpoint}}/batch/status


### 개발용 컨트롤러 : batch job status search for jobId
GET {{endpoint}}/batch/job/72



### 개발용 컨트롤러 : bull queue 실패한 데이터 삭제처리
DELETE {{endpoint}}/batch/failed



### 개발용 컨트롤러 : bull queue 완료된 데이터 삭제처리
DELETE {{endpoint}}/batch/completed



### 개발용 컨트롤러 : bull queue 전체 이력 삭제처리
DELETE {{endpoint}}/batch/all



### 개발용 컨트롤러 : 정류장 노선 업데이트 배치 수동요청
POST {{endpoint}}/batch/bus-tracking
Content-Type: application/json


### 개발용 컨트롤러 : 정류장 노선 트래킹 수동 요청
POST {{endpoint}}/bus/tracking
Content-Type: application/json

{
    "stationId": "218000165",
    "routeId": 229000023,
    "routeName": "9710",
    "notificationTime": ["09", "10", "11"]
}