http:
  port: 3000

mongo:
  url: 'mongodb://mongo:test@localhost:27017/stop-line-monitor?authSource=test'
  username: 'mongo'
  password: 'test'

publicApi:
  stationInfoUrl: 'https://openapi.gg.go.kr/BusStation'
  serviceKey: '' # 경기 데이터 드림 사이트 인증키
